version: '3.8'
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    container_name: n8n-email-manager
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Madrid
      - TZ=Europe/Madrid
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=n8npassword
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_LOG_LEVEL=info
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID  
    volumes:
      - ./n8n-data:/home/node/.n8n
      - ./data:/home/node/data
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:5678/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
networks:
  default:
    name: n8n-network
